[package]
name = "in-cells"
version = "0.1.0"
edition = "2024"

[dependencies]
dunge-winit = "0.3.8"
futures-concurrency = "7.6.3"
image = { version = "0.25.6", default-features = false, features = ["png"] }
